name: Deploy to Minikube
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          
      - name: Build and push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build -t $DOCKER_USER/flask-app:latest .
          docker push $DOCKER_USER/flask-app:latest
          
      - name: Deploy
        run: kubectl apply -f k8s-deployment.yaml
